language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

cache:
  directories:
    - node_modules

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - set -ev
  - export TZ='Asia/Shanghai'
  - git config user.name "zkphyj"
  - git config user.email "zkphyj@163.com"
  - git clone https://github.com/zkphyj/zkphyj.github.io .deploy_git
  - cd .deploy_git
  - git checkout master
  - mv .git/ ../public/
  - cd ../public
  - git add .
  - git commit -m "Site updated:`date +"%Y-%m-%d %H:%M:%S"`"
  - git push "https://${GH_TOKEN}@github.com/zkphyj/zkphyj.github.io.git" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - hexo  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置